language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: netlify
  site: $NETLIFY_SITE_ID
  auth: $NETLIFY_AUTH_TOKEN
#  edge: true # opt in to dpl v2
  local_dir: "build/"
  prod: true
  on:
    all_branches: true