language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - echo $TRAVIS_COMMIT_MESSAGE $TRAVIS_BUILD_WEB_URL $TRAVIS_JOB_WEB_URL;

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy --dir=./build --prod --site $NETLIFY_SITE_ID_PROD --auth $NETLIFY_AUTH_TOKEN
  skip_cleanup: true
  on:
    all_branches: true