language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    all_branches: true