language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test

before_deploy:
  - npm run build

deploy:
  - provider: script
    script: ./node_modules/.bin/netlify deploy --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir ./build -m $TRAVIS_COMMIT
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir ./build -m $TRAVIS_COMMIT
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != master
